In [8]:
import pandas as pd
from pathlib import Path

DATA = Path("data")

def raw(name, **kw):
    return pd.read_csv(DATA  / name, dtype=str, keep_default_na=False, na_filter=False, **kw)

In [10]:
h1 = raw("trips_2025_H1.csv")
print("h1:", h1.shape)
h1.head()

h1: (14200, 10)

,trip_id,trip_datetime,driver_id,vehicle_id,pickup_zone,dropoff_zone,distance_km,duration_min,fare_eur,payment
0,T11000000,2025-01-25 03:47:00,DR-1050,VH-025,Port,Centre,3.52,14.1,"11,40",wallet
1,T11000001,2025-04-01 14:36:00,DR-1009,VH-037,Airport,West,10.09,47.8,"28,39",wallet
2,T11000002,2025-05-09 00:29:00,DR-1020,VH-023,Centre,North,2.5,14.2,"10,25",CASH
3,T11000003,2025-01-27 09:55:00,DR-1036,VH-026,North,Centre,4.31,19.1,"13,70",card
4,T11000004,2025-04-10 01:32:00,DR-1053,VH-026,Suburbs,Suburbs,9.18,33.2,"23,25",wallet

In [11]:
h2 = raw("trips_2025_H2.csv")
print("h2:", h2.shape)
h2.head()

h2: (16280, 11)

,trip_id,trip_datetime,driver_id,vehicle_id,pickup_zone,dropoff_zone,distance_km,duration_min,fare_amount,payment,platform
0,T22000000,19/11/2025 08:39,DR-1063,VH-030,Port,Suburbs,5.63,30.6,EUR 18.44,CASH,Direct
1,T22000001,06/08/2025 22:05,DR-1009,VH-041,Airport,Suburbs,12.47,56.3,EUR 33.50,wallet,CityHail
2,T22000002,18/08/2025 15:00,DR-1002,VH-018,Centre,Airport,5.3,25.4,EUR 16.61,Card,Direct
3,T22000003,23/09/2025 03:59,DR-1046,VH-018,Suburbs,Suburbs,3.77,18.6,EUR 12.94,card,RideGo
4,T22000004,30/08/2025 20:19,DR-1016,VH-040,Port,Suburbs,4.53,16.2,EUR 13.15,cash,CityHail

In [13]:
h3 = raw("trips_2026_H1.csv")
print("h3:", h3.shape)
h3.head()

h3: (15400, 1)

  trip_id;trip_start_utc;driver_id;vehicle_id;pickup_zone;dropoff_zone;distance_km;duration_min;fare_amount;payment;platform;surge_multiplier
0  T33000000;2026-06-09T10:22:00+03:00;DR-1022;VH...
1  T33000001;2026-04-13T19:54:00+03:00;DR-1055;VH...
2  T33000002;2026-02-24T06:31:00+03:00;DR-1010;VH...
3  T33000003;2026-04-17T06:21:00+03:00;DR-1066;VH...
4  T33000004;2026-06-17T18:51:00+03:00;DR-1063;VH...

In [14]:
h3 = raw("trips_2026_H1.csv", sep=";")
print("h3:", h3.shape)
h3.head()

h3: (15400, 12)

,trip_id,trip_start_utc,driver_id,vehicle_id,pickup_zone,dropoff_zone,distance_km,duration_min,fare_amount,payment,platform,surge_multiplier
0,T33000000,2026-06-09T10:22:00+03:00,DR-1022,VH-023,North,North,5.02,14.8,13.32,wallet,CityHail,1.0
1,T33000001,2026-04-13T19:54:00+03:00,DR-1055,VH-011,West,Centre,8.1,32.3,21.76,card,Direct,1.0
2,T33000002,2026-02-24T06:31:00+03:00,DR-1010,VH-040,East,East,11.09,34.7,46.57,cash,Direct,1.8
3,T33000003,2026-04-17T06:21:00+03:00,DR-1066,VH-009,Centre,Centre,7.7,23.6,18.86,card,CityHail,1.0
4,T33000004,2026-06-17T18:51:00+03:00,DR-1063,VH-041,East,Suburbs,10.42,52.6,36.13,wallet,Direct,1.2